apply plugin: 'com.android.application'

repositories {
    google()
    mavenCentral()
}

android {
    compileSdkVersion 35
    buildToolsVersion '35.0.0'
    
    // هویت داخلی کدها را به نام اصلی برمی‌گردانیم تا خطا ندهد
    namespace 'org.telegram.messenger'

    defaultConfig {
        // هویت نصب برنامه روی گوشی همچنان نام اختصاصی توست
        applicationId "org.infinity.tel"
        minSdkVersion 21
        targetSdkVersion 35
        versionCode 1
        versionName "1.0"
        ndkVersion "21.4.7075529"
        multiDexEnabled true

        externalNativeBuild {
            cmake {
                version '3.10.2'
                arguments '-DANDROID_STL=c++_static', '-DANDROID_PLATFORM=android-21'
            }
        }
    }

    sourceSets {
        main {
            java.srcDirs = ['../TMessagesProj/src/main/java']
            jniLibs.srcDirs = ['../TMessagesProj/jni/']
            manifest.srcFile '../TMessagesProj/config/release/AndroidManifest.xml'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug // فعلاً از امضای دیباگ استفاده کن تا خطای کلید ندهد
        }
    }
}

dependencies {
    implementation project(':TMessagesProj')
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'
    implementation files('../TMessagesProj/libs/libgsaverification-client.aar')
}
